### ISSUE TITLE
Crash when using chat

### ISSUE THREAD

**Issue by Xleby4ek** [TheCSDev/mc-better-stats#9] opened 2022-09-17 06:49 UTC
Hello, I really liked your mod, but unfortunately I can't use it because of a bug in which if you write something in the chat, the game crashes immediately, please fix it.

**Comment by TheCSDev** [comment] 2022-09-17 07:17
Hello. Thank you for your feedback. I would love to work on resolving this crash as soon as possible. Unfortunately, you have not provided me with enough information to work with. The only way I can resolve this crash is by knowing what exactly caused it, which I don't. So it would help a lot if you published a log file as well as a crash report file alongside this issue. That way I can take a look at them and see what exactly is causing the crash.<br/>
Now of course, when I play-tested this mod in both vanilla Minecraft as well as modded Minecraft (with mod packs), there were no issues with chat crashing the game, so I am assuming this mod conflicts with another mod, causing the crash. If that is the case, then I would like to try and resolve this conflict. The only way I can know for sure on what the issue is - is if I get a crash report file, so I would like to ask you if you could send me one.<br/>
Thank you again for the bug report, and have a nice day.

**Comment by Xleby4ek** [comment] 2022-09-17 08:38
After reinstalling the mod, everything worked correctly, apparently it was somehow connected with the incorrect loading of the mod

**Comment by TheCSDev** [comment] 2022-09-17 09:01
Sounds good. I'm glad you managed to get the issue resolved. Feel free to let me know if you encounter any other issues with the mod. Have a great day.

**Closed by TheCSDev** 2022-09-17 09:01 UTC
